### ISSUE TITLE
Save issue on cartridge

### ISSUE THREAD

**Issue by Ataloumpak** [d3m3vilurr/vita-savemgr#1]
I tried to extract a save from physical version of P4G. But i run into an error each time it tries to lauch the game, saying i need a psvita card containing the app. And when i launch the psvita, it says that the install of savemgr has failed, that the icon is allready installed. during the message, this app has p4g icon at this moment.
How do i fix this problem?

**Comment by d3m3vilurr** [comment]
ah....actually you need real cartridge, i will add guard code for this if i can...
anyway you cannot launch game, restart savemgr, i think it will fix game launch problem.

detail explain:
this application replace your game binary before extract savedata like vitamin.
then auto launch game(actually open dumper) and when you exit dumper(not manually) return savemgr automatically then clean up injected binaries.

so you just reopen savemgr it will remove injected binary.
or insert cart then restart p4g, will launch dumper.

**Comment by Ataloumpak** [comment]
Ok, so you need to actually remove any cartridge from slot in saveMgr, then reinsert it always in savemgr, then launch the dumper.
So it means :
-Launch the savemgr app.
- Remove any cartridge.
- insert game cartridge.
- Launch dump of save.

Then the game will work again.

Thanks for the tips :)

**Comment by d3m3vilurr** [comment]
Fixed 4036189c0
and new version released https://github.com/d3m3vilurr/vita-savemgr/releases/tag/0.3
thx bug report :D
