### ISSUE TITLE
save manager broke 

### ISSUE THREAD

**Issue by useresc** [d3m3vilurr/vita-savemgr#103]
[](url)
![PXL_20211016_171921987~2](https://user-images.githubusercontent.com/92645135/137596914-f2b9faa8-36c1-4fa5-9a03-e32be02661b7.jpg)
![PXL_20211016_171905280~2](https://user-images.githubusercontent.com/92645135/137596917-c946a205-5058-4df4-9273-408f3783298b.jpg)
After leaving vita in sleep mode in adrenaline for a while, save manager bubble got corrupted. After reinstalling while keeping the config file, I can't change settings and use previous backups.

**Comment by d3m3vilurr** [comment]
did you use sdcard plugin?

**Comment by useresc** [comment]
> 

Yes. I'm using yamt plugin.

**Comment by d3m3vilurr** [comment]
it would be pretty related sdcard plugin problem.
btw, if you use nightly savemgr, you are able to change backup place to ur0 or somewhere via changing config file. `ux0:/data/savemgr/config.ini`
actually, i'm not recommand to use sdcard as replacing the ux0 memory of the vita.
