### ISSUE TITLE
0.41 can export YS8 but 0.50 failed

### ISSUE THREAD

**Issue by WanderMax** [d3m3vilurr/vita-savemgr#13]
0.41 can export YS8 but 0.50 failed

**Comment by WanderMax** [comment]
0.50: inject fail
0.41: success

**Comment by d3m3vilurr** [comment]
can you share your app.db? if can, send email to d3m3vilurr at gmail.com

**Comment by WanderMax** [comment]
PSV1000 
dumped YS8, decrypted
how to get the app.db?

**Comment by d3m3vilurr** [comment]
`ur0:shell/db/app.db`

**Comment by WanderMax** [comment]
OK  wait

**Comment by WanderMax** [comment]
send you mail.

**Comment by d3m3vilurr** [comment]
ok, i have a question, can you remember about encrypt feature(import save) success or not on 0.4.1?

**Comment by WanderMax** [comment]
I just try to export the save data of YS8, and 0.50 fail with can not inject.
0.41 can export the sava data.

**Comment by d3m3vilurr** [comment]
hm... ok can you test inject save on 0.4.1?
but you need to backup with QCMA.. i can restore old code, but i reported cannot re-encrypt save like this issue

**Comment by WanderMax** [comment]
I will try to import the modified save data, and game say save data broken.
terrible~~

**Comment by WanderMax** [comment]
try again, still broken.....

**Comment by WanderMax** [comment]
if do no modification ti the save data, game can read it.

**Comment by d3m3vilurr** [comment]
ok
- on 0.4.1; can decrypt, cannot encrypt
- on 0.5.0; can't both
right?

**Comment by WanderMax** [comment]
wait, I doule confirm whether it is the issue of the save data cheater tool.

**Comment by WanderMax** [comment]
doule checked, for YS8 with 0.41, decrypt and encrypt both right.
I forget to add checksum to save data, which result the broken data. sorry.

0.50 decrypt failed, encrypt  not tested.

**Comment by d3m3vilurr** [comment]
huh....are you also check this?
play something & save, then import
so my question, your save can return from last save point.
if can this, i will just recover old code :)
that will resolve this issue.

**Comment by WanderMax** [comment]
I think this may be the special case that only old version can work.
in my previous test, I do modification to my save data via cheat tool, add checksum, then import, can play game well and save data again.

**Comment by foxhidden2009** [comment]
Hello, I have similars problem with my FFX Remaster catridge saves:
In the savemgr_0.4.1 I can export my saves correctly and when I choose to import I have the message "import to savedata0: ..." wait a few seconds, "done please press circle" and I have my saves.
In the version 0.5.0 I do the same thing and I have the message "Import to ux0:/data/rinCheat/PCSB00395_SAVEDATA..." and I have nothing... it's not normal right?

**Comment by d3m3vilurr** [comment]
alright friends :(

i made something mess on the 0.5.0.
this version not work import process (actually require to purge save directory before import)
and i was luck could found reason :)

so i already fixed on my local repo, and also lucky, may fix this issue.
i sended new build to @WanderMax & @ness151 for check.
i just wait this result.

so i'll release new build at tomorrow. please wait.

PS. @foxhidden2009 your issue looks new, but i guess, your issue also resolved.

**Comment by WanderMax** [comment]
@d3m3vilurr tested, new version can import save data now.
however, could you please add app icon and version number? now the version in sfo is 0.00.
and for failed case, maybe you can implant the fix tool to delete eboot.bin and rename  eboot.bin.org to  eboot.bin. it can be friendly to do it in your app.
thanks.

**Comment by d3m3vilurr** [comment]
hi .
that's long term plan :)

2016. 9. 22. 오전 9:46에 "WanderMax" <notifications@github.com>님이 작성:

**Comment by WanderMax** [comment]
@d3m3vilurr hahaha, yes, but it will be nice with the embedded fix tool, just one button press on selected game.

**Comment by d3m3vilurr** [comment]
Close. also `APP_VER` will add 50f5ead3 :)

**Comment by WanderMax** [comment]
great, how about app icon?
maybe one beautiful icon is needed.

**Comment by d3m3vilurr** [comment]
i'm not artist. so i need CCL or public domain image. can you suggest? :-/

**Comment by WanderMax** [comment]
http://www.iconarchive.com/show/drifting-icons-by-harwen/Saved-Data-Utility-icon.html
http://www.iconarchive.com/show/database-icons-by-fasticon/data-edit-icon.html
http://www.iconarchive.com/show/crystal-clear-icons-by-everaldo/Action-db-update-icon.html

maybe you can check others
