### ISSUE TITLE
Issue with Criminal Girls

### ISSUE THREAD

**Issue by williamvun** [d3m3vilurr/vita-savemgr#15]
After dumped the savegame, I went back to play it but it displaying the same thing when it dumping the game. It doesn't allowed me to play it. http://imgur.com/a/0IPor. This issue still the same from 0.5.0.

**Comment by d3m3vilurr** [comment]
just press exit :(
app will automatic return to savemanager and will clean up injected data.

if you still got problem, please follow [emergency-guide](https://github.com/d3m3vilurr/vita-savemgr#emergency-guide)

**Comment by williamvun** [comment]
Ok that's solve it. I thought it would just quit by its own like the others. And 0.6 have to manually enter the selected game in order to dump it instead of it enter the game by its own. Is this normal?

**Comment by d3m3vilurr** [comment]
i'm sorry, hard to understand for me...

you mean, dumper started for `dumped` game, but you want retail?

**Comment by williamvun** [comment]
Nvm, it seems I need to restart few times for it to work. All work fine now :) :+1:
