### ISSUE TITLE
Can't load save

### ISSUE THREAD

**Issue by rikimtasu** [d3m3vilurr/vita-savemgr#2]
It seems that it can't read dumped save.
On henkaku v6.

**Comment by d3m3vilurr** [comment]
can you leave more detail information?

**Comment by rikimtasu** [comment]
Had game dumped by maidump and vitamin,saves on ux 0:user/
No encrypted game.
On the app it doesn't show any game and when I press anything it crash with 1-1288 kind of error

**Comment by d3m3vilurr** [comment]
hmm... what game?

**Comment by rikimtasu** [comment]
Maidump :
SAO HF Asian ver
Atelier Shalie plus

Vitamin2.0:
Disgaea 3
Disgaea 4

**Comment by d3m3vilurr** [comment]
it's strange.. can you share your crash dump to d3m3vilurr at gmail.com?

**Comment by d3m3vilurr** [comment]
I don't know why you not printed anything, so i need your app.db for detail figure out.
btw, i add to print error code and guide null point exception b667af9b84

**Comment by d3m3vilurr** [comment]
this patch will fix your problem. i will release new version after check another issues. thank. :) 18dec6e9b79f

**Comment by rikimtasu** [comment]
thanks man
