### ISSUE TITLE
Deleting Save of a game

### ISSUE THREAD

**Issue by Catarax** [d3m3vilurr/vita-savemgr#22]
I expected to be able to delete the current save of a game because i'm using a "save manager".

At the end, I have to do this by the hand on VitaShell, please include this feature!

**Comment by d3m3vilurr** [comment]
i already have plan about dropping save-slot.
but i guess, you want just formatting save of the current playing game, right?
yea, I'll make this feature, too ;)

**Comment by Catarax** [comment]
Yes, this is about formatting the save of a current game since this feature doesn't exist at all on the vita.
Thanks!
