### ISSUE TITLE
pcse00880 woff error 0x8001000D

### ISSUE THREAD

**Issue by 00junn** [d3m3vilurr/vita-savemgr#26]
0.8.0 924D1DA
pcse00880 woff
 error 0x8001000D

**Comment by Traace** [comment]
^
+
PCSF00012: Uncharted: Golden Abyss
error 0x8001000D
Versions: 0.8.0 & 0.8.0-924d1da (nightly)

**Comment by d3m3vilurr** [comment]
please share detail error info.
- what action occur error?
- what type game media?

**Comment by Traace** [comment]
Here are more information for this error code.
First of all, i realized this has nothing to do with vita-savemgr.
The bug called "memory card IO bug" and it also prevent vitashell to access these files.
I guess that the system denies write access to ux0:\ and therefore it outputs this error.

A standard reboot fixed this issue for me. No database rebuild is needed. However we have to "re-henkaku" it ofc.

Close request

**Comment by d3m3vilurr** [comment]
alright. thx info :)
