### ISSUE TITLE
Download title (Senran Kagura Estival Versus JPN) does not launch dumper mode

### ISSUE THREAD

**Issue by Bryan-Low** [d3m3vilurr/vita-savemgr#27]
I have a copy of SKEV I had bought from the japan psn that for some reason refuses to enter dumper mode and simply launches the game as per normal.
I tried testing it on a different downloaded title I had, Sword Art Online Lost Song, and it managed to enter dumper mode and dump the save. 
Tested it on both 0.7 and 0.8 without any success.

**Comment by d3m3vilurr** [comment]
sorry. i haven't skev. so i can't help now like #25 
i guess this problem look similar #4 
anyway problem only have retail dl title? can check dump program?
