### ISSUE TITLE
Can't detect save/Dump's empty folder

### ISSUE THREAD

**Issue by ness151** [d3m3vilurr/vita-savemgr#3]
This is a more common issue with games that have English Asian releases (Gundam Breaker 3 is the most notorious of these)

It'll dump the titleID the game uses to launch, but not the titleID the game uses to save.

Gundam Breaker 3 
-Game TitleID PCSH00208
-Save TitleID PCSG00760

**Comment by d3m3vilurr** [comment]
you can dump but cannot use import right?

**Comment by ness151** [comment]
No.  It doesn't dump the correct directory.  It dumps an empty folder.

**Comment by d3m3vilurr** [comment]
hm. that's strange. maybe that game not use savedata0.... i will check this

**Comment by ness151** [comment]
Thank you.
