### ISSUE TITLE
Cannot earn trophies if not play game before import

### ISSUE THREAD

**Issue by szczuru** [d3m3vilurr/vita-savemgr#31]
Recently i've switched my account on vita. Before that i've backuped all saves with this awesome tool but now after restoring them on new account i can't earn trophies (i think due to other PSID in param.sfo or something like that). Is there any way to resign those saves to my new account?

**Comment by d3m3vilurr** [comment]
well.. that's already known issue.
imported save cannot unlock trophies. (also current not have plan about this)
but, i guess still can have problem in unlocking trophy feature like sync psn

**Comment by szczuru** [comment]
You missunderstood me - i don't wan't to unlock trophies earned before (on old psn profile) but i want to be able to get (new) trophies playing on imported saves. Eg i have save from old profile from Uncharted (game not completed, about ~3h of playing), when i load it on new profile i've got toast message that i can't earn trophies using this save.

**Comment by d3m3vilurr** [comment]
i'm not yet try RE `SceTrophy`, so don't know real reason.
but if game logic(or system logic) check earned trophy, it can make no more gain next trophies.
so i said `unlock`. :/

**Comment by szczuru** [comment]
I've figured it out!

Just deleted all Uncharted saves from vita, started new game and saved (everything was done on new profile). Save dumped via Save Manager and replaced all files in SLOT0/slot_000 with files from old save (from previous profile). So sce_sys was from new profile and everything else was from old profile - now i can earn trophies :D
