### ISSUE TITLE
Change wordings to avoid confusion

### ISSUE THREAD

**Issue by masterrite** [d3m3vilurr/vita-savemgr#32]
Hi,

Cab we change "import" and "export" options into "restore" and "save", or have instructions about what "import" and "export" does on the screen?

I was confused about these options, and just tonight, when I finished a session on YS VIII (which is in a cartridge), I accidentally hit "import" instead of "export", and overwrote my new save with the one from last night. I think it'd be clearer to change them or have on-screen instructions.

Thanks!

**Comment by Schadows** [comment]
Seconded.

Import or Export isn't clear enough depending on your perspective (is it exporting from the game into Save Manager (save / backup) or from Save Manager to the Game (restore) ?
The current words are ambiguous, so I had backup my saves with QCMA before trying the first time.

**Comment by d3m3vilurr** [comment]
I'll change `backup & restore`. it looks better ;)

**Comment by masterrite** [comment]
Thanks!
