### ISSUE TITLE
 initialization error, fffffffd on startup

### ISSUE THREAD

**Issue by Waliers** [d3m3vilurr/vita-savemgr#33]
Version 0.6.0 and 0.8.0
Worked in the past multiple times after reinstall of henkaku it doesnt work.

Tried removing and reinstalling the program still red letters at boot with  initialization error, fffffffd.

**Comment by d3m3vilurr** [comment]
can you check enabled unsafe app option?

**Comment by Waliers** [comment]
SOLVED! Thanks! Don't know what turned it off since I didn't turn in on or off on after install but it works. Again thanks for the response and the wonderfull software!
