### ISSUE TITLE
Save manager Stuck!

### ISSUE THREAD

**Issue by TheBorder** [d3m3vilurr/vita-savemgr#35]
I open the app select game then open the game and stays at the game's boot logo.?

**Comment by d3m3vilurr** [comment]
can you share version & game?

**Comment by TheBorder** [comment]
I had 0.8.0 and yesterday i changed to beta.
Gravity Rush & Arkam & Wipeout 2048.

**Comment by d3m3vilurr** [comment]
both version are same?
are you use taihen plugin like oclock vita?

**Comment by TheBorder** [comment]
No i had https://github.com/d3m3vilurr/vita-savemgr/releases/tag/0.8.0 and now i have https://github.com/d3m3vilurr/vita-savemgr/releases/tag/nightly

Yes i use oclock.

**Comment by d3m3vilurr** [comment]
can you check after disable oclock?
i heard conflict report about oclock.

**Comment by TheBorder** [comment]
ok

**Comment by TheBorder** [comment]
Thank you it worked perfectly. :)

Can this conflict be fixed?

**Comment by d3m3vilurr** [comment]
It's related frangarcj/oclockvita#4
I'm not analysis that project. so I don't know yet.

**Comment by TheBorder** [comment]
ok thx
