### ISSUE TITLE
Dumper won't get past loading

### ISSUE THREAD

**Issue by vipertongn** [d3m3vilurr/vita-savemgr#36]
The app was able to work initially until I decided to reformat my memory card and start from scratch.  I launch the app and select the game.  After it switches to the game loading screen, it gets stuck.  I can close the app and do the emergency guide to play the game as normal.  I'm not sure why I'm unable to back up saves.  I've tried uninstalling the game and the manager, reinstalling everything,  then starting a new game,  also tried qcma transferring everything.  For some reason, it will no longer back up my files

**Comment by d3m3vilurr** [comment]
can you leave more detail information?

**Comment by d3m3vilurr** [comment]
please share these infos

1. what game
2. what use savemgr version
3. are you use custom taihen plugins?

**Comment by vipertongn** [comment]
thanks for the quick response.
1. atelier meruru plus
2. the latest version (nightly)
3. I'm using oclock so far with R7 of henkaku

**Comment by d3m3vilurr** [comment]
what version oclock?
please check with oclock 1.2.1 (if you not use this version)
if still stuck, please retest after disable this plugin.

some taihen plugins can break homebrews :/

**Comment by vipertongn** [comment]
I think i'm on 1.2 (not sure because the file doesn't have the version name)  I'm reinstalling the game because it was corrupted after attempting save manager.  Will report  in a few min

**Comment by vipertongn** [comment]
I replaced my oclock file with the 1.2.1 file, and restarted the system.  This deleted the eboot for that particular game.  I replaced the eboot with another copy I backed up because I ran into it earlier.

I then removed the oclock from the config text (then restarted).  I am able to properly use the save manager, but I guess one of my save slots became corrupted. Most likely due to the plug in :/.  Is the save manager compatible with oclock?

**Comment by d3m3vilurr** [comment]
1. in before i said, plugin can break compatibility, it cause application module apis.. i don't know generic solving method for this problem.
easy way, support more apis in savemgr, but it'll make increasing program size. so i'm not want to this. (but still considering this..)

    few days ago, i made patch to oclock(and patch included in 1.2.1)
but it looks made another problem in oclockvita.

    anyway, it's actually not a vita-savemgr bug, just taihen plugin problem. :(
these problem can impact to all homebrews if plugin applied all apps.

2. i'm not tested with amphetamine. but i guess they can work :)
cuz these plugins(like amphetamine) loaded from game. but taihen plugins loaded from vita henkaku system.
so, taihen plugin also loaded in injecting savemgr, but amphetamine is not loaded in savemgr

**Comment by vipertongn** [comment]
I think amp gets loaded too but it's not as bad

**Comment by vipertongn** [comment]
Like I had a corrupted save file at least probably due to the plug-in. This is unfortunate because overclocking makes game play that much smoother

**Comment by vipertongn** [comment]
Also I didn't set for all. I had the plug-in for oclock set for just meruru

**Comment by vipertongn** [comment]
Thanks so much for your help in isolating the problem. At least now I can play my games with backups. Just dealing with some lag
