### ISSUE TITLE
Some cartridge games(eg. muramasa rebirth) cannot launch dumper mode

### ISSUE THREAD

**Issue by asdion** [d3m3vilurr/vita-savemgr#4]
![2016-09-16-121820](https://cloud.githubusercontent.com/assets/10775546/18583841/652d0600-7c0d-11e6-8c92-4b96c87dac1e.jpg)
![2016-09-16-121831](https://cloud.githubusercontent.com/assets/10775546/18583842/6533cf3a-7c0d-11e6-8d6e-4f67947da716.jpg)

After that it opens the game itself but instead of switching back to the manager it stays on the app
i had no problems dumping from a dumped game the problem came only with the cart version of Muramasa Rebirth

**Comment by d3m3vilurr** [comment]
I guess, it will fixed 117df8d75bc. please check with [0.4.1](https://github.com/d3m3vilurr/vita-savemgr/releases/tag/0.4.1)

**Comment by asdion** [comment]
Sadly the problem still persists
the only thing that changed can be seen in the screenshot
![2016-09-17-102534](https://cloud.githubusercontent.com/assets/10775546/18607079/52b24d18-7cc2-11e6-848f-c4bd737f0c62.jpg)
after this it opens the game but doesn´t switch back to the manager

**Comment by d3m3vilurr** [comment]
please share your `ur0:shell/db/app.db` to email. d3m3vilurr at gmail.com.
it's too strange situation...

**Comment by asdion** [comment]
the email is sent

**Comment by d3m3vilurr** [comment]
can you test [urlcaller](https://github.com/Freakler/vita-uriCaller/releases)
input `psgm:play?titleid=PCSE00240`, then share result about start game.

**Comment by asdion** [comment]
doing that the game simply starts as if i had started it normally after asking me to close the urlcaller

**Comment by d3m3vilurr** [comment]
i don't know why stuck there..
please check this, wait few sec after print `DO NOT ....`, then close app force, start your game manually.
then share result.

**Comment by asdion** [comment]
i can not wait for a few seconds after "do not..." because the app itself opens the game 
as i mentioned above it does open the game but it doesn´t switch back to the manager afterwards

i´ve to close the app before it can start the game and then start the game manually and there´s nothing special happening the game starts normally

**Comment by d3m3vilurr** [comment]
ah. now understand real issue. you mean, you cannot see dumper menu, cuz game start normally, right?

**Comment by asdion** [comment]
pretty much yes
after what is in my last screenshot happens
the game starts normally

**Comment by d3m3vilurr** [comment]
ok, can you share `gro0:app/PCSE00240/sce_sys/param.sfo` & `ux0:patch/PCSE00240/sce_sys/param.sfo` if exists

**Comment by asdion** [comment]
yes both exist and i sent them per email 
i added gro0-- and ux0-- to the name so you can recognize which one is which

**Comment by Sir-Charles** [comment]
I'm also having this issue with legit US cart of Ultimate Marvel Vs Capcom 3 PCSE00004. It opens the game and then stays there, not switching back to the dumper.

**Comment by apizzamra** [comment]
Hi, i confirmed this bug also happen on dynasty warrior cartridge version...

**Comment by asdion** [comment]
Dunno if this is anything new or useful but it's the only method that worked for me.
The savedata can be plainly copied out of the grw0 partition and thrown into ux0:user/00/savedata
Then you have to get the game to run as a nonpdrm dump which should be able to recognize the save and then you can use the savemgr to dump the save properly.
This at the very least works with Muramasa Rebirth.

**Comment by NijiBashira** [comment]
I asked about this on GBATemp and got this answer : 

      "The physical version of this game saves on grw0. The patch is also located in grw0. Usually, to dump save, the save manager replaces the patch in ux0. But in this case, grw0 patch is started first. So you need to manually copy the save manager patch from ux0 to grw0. Then, restart the game: the save manager should start instead. Once you get your save, don't forget to put back the original patch in grw0."

So what I did is : 
- Start Vita-savemgr and select Muramasa (with the cartridge inserted)
- Once Muramasa starts normally, exit and close it.
- Start Vita Shell and go to grw0:patch/
- **BACKUP THE PCSE00240 FOLDER**
- Go to ux0:patch/ and **copy** the PCSE00240 folder
- Paste it in grw0:patch/
- Start the game, the dumper should start

Once you're done, restore the grw0:patch/PCSE00240 folder to the backup you made.

Notes : 
- I only tested this on Muramasa, so I don't know if it'd work for other games.
- PCSE00240 is the Title ID of the US version of Muramasa. It will be different for other versions of the game and (obviously) other games.

**Comment by d3m3vilurr** [comment]
no more use app switching
