### ISSUE TITLE
Error 0x80010000

### ISSUE THREAD

**Issue by SPMelly** [d3m3vilurr/vita-savemgr#40]
Im getting this error on my phat vita. On my slim it works just fine but not on my phat. Any advice?
Game im trying to backup save of is Uncharted if that matters

**Comment by d3m3vilurr** [comment]
Can you recheck unsafe app option in molecular shell?

**Comment by SPMelly** [comment]
yup just tried that

**Comment by d3m3vilurr** [comment]
well... that's weird. can you just reset on your vita?

**Comment by SPMelly** [comment]
Weird. I rebooted before and it still didnt work but i rebooted yet again and now its working

**Comment by d3m3vilurr** [comment]
it looks not a savemgr bug. :)

**Comment by SPMelly** [comment]
Lol well thanks for the help. Got a donation link?

**Comment by d3m3vilurr** [comment]
you can donate using bitcoin to 1Efy5rh2Z1vXwfqXGhVhwk76WhiWVU3DWo
or can use paypal http://paypal.me/d3m3vilurr 
thanks
