### ISSUE TITLE
"Cannot find inject data"

### ISSUE THREAD

**Issue by julienkoenig** [d3m3vilurr/vita-savemgr#41]
I've dumped "Soul Sacrifice Delta" (-buyed PSN) save with the last nightly build, like Minecraft (own Vitamin dump)
Now I can't start Soul Sacrifice Delta (SSD) anymore, I allway get the message "Cannot find inject data". If i press (X) it opens save manager and that's it. 
I've looked in different folders of the game (app; appmeta; patch; user/00/savedata; ) but found nothing weird (like _org files or something)
I've tried deleting the nightly and installed the last stable (0.80.0), but it didn't help.
I can still dump/restore, but changes nothing.
Rebuild database doesn't help either. 
If i start it without Henkaku, i get an error ((C1-6775-5) weird part is the Application: NPXS19999 )
The save is important to me (that's why i made a backup) but it looks like it's gone. :-(

Btw. I cannot just reinstall the game, it's over 3 Gigabyte, it would take over a week to download it again..

**Comment by julienkoenig** [comment]
Okay, the error code seems to be normal cause it tries to open save manager without henkaku activated...

**Comment by julienkoenig** [comment]
If looked closer on the patch/PCSF00532/ folder (SSD) , on first it didn't look weird, but then i've seen it's to small, so i opened all files and... besides the param.sfo they are all save manager files. 
Did the save manager exchange these files?
And when yes, where are the original?
Probably the nightly doesn't changed back, that would explain why i still can dump and restore..

**Comment by julienkoenig** [comment]
I looked in every folder of ux0: , nothing.
The original patch is gone. 
If i delete the fake patch, it starts, but unpatched, still it think it is, therefore i can't download it again. But that's probably something that i've to solve myself.
My bad for using the nightly

**Comment by DevinCampbell** [comment]
I received a similar message. I ended up having to delete the game and all my save files, and then installing the game again to play it.

**Comment by DevinCampbell** [comment]
After testing, it appears this is only happening on the most recently "nightly" build. The last stable build doesn't do this.
