### ISSUE TITLE
C++ compatibility

### ISSUE THREAD

**Issue by devingDev** [d3m3vilurr/vita-savemgr#47]
Hi there, could this be made to function with C++ ?

I think it does not work as it is when trying to compile as a C++ project.

**Comment by d3m3vilurr** [comment]
why?

**Comment by devingDev** [comment]
I wanted to add some things to it but I use C++ and idk if I could do it in
C. Like this library is in C++ which zips folders. Its called zipper

**Comment by devingDev** [comment]
Maybe I am just making this complicated. If so tell me.

On 30 Aug 2017 2:08 pm, "Alex C." <bizzy933@googlemail.com> wrote:

I wanted to add some things to it but I use C++ and idk if I could do it in
C. Like this library is in C++ which zips folders. Its called zipper

**Comment by d3m3vilurr** [comment]
I don't understand your question.
Do you want my project turn to C++, or want my file use to your project?

**Comment by devingDev** [comment]
I just wanted to use some C++ libraries in your project, thats why I needed it to be C++ but I do not need it anymore I just had to add certain things.
