### ISSUE TITLE
NpNoDrm dump game did not cleanup injected patch

### ISSUE THREAD

**Issue by SquallATF** [d3m3vilurr/vita-savemgr#48]
Use savemgr with NpNoDrm dump game, the injected patch dit not restore, mast manul remove injected patch directory , if have original patch also need manual rename patch directory to original

**Comment by WanderMax** [comment]
@d3m3vilurr maybe need to implant the method to restore the save between mai/vai dump<->NpNoDrm ones.

**Comment by SquallATF** [comment]
@WanderMax Run mai/vai dump backup save, remove mai/vai dump game and install NoNpDrm dump, and then restore save can work.

**Comment by d3m3vilurr** [comment]
all nonpdrm games can't restore?

**Comment by SquallATF** [comment]
@d3m3vilurr can restore, but savemgr can not auto remove injected patch

**Comment by d3m3vilurr** [comment]
ah got it. have all games a same issue? i'm not test NoNpDrm yet cuz my vita issue.

**Comment by SquallATF** [comment]
@d3m3vilurr I did not known, because decrypted game only rename eboot.bin. I think may be encrypted game have this issue, I did not test cartridge game.

**Comment by AldarisX** [comment]
My PCSH00050(Dragon`s Crown) tip The file is corrupt(C1-2738-0)

**Comment by kathampy** [comment]
Only Nightly 144 is broken and does not clean up the patch. 0.8.0 stable cleans up fine.

**Comment by AizenSousuke** [comment]
@kathampy 0.8.0 also doesnt clean up...

**Comment by hugo-id** [comment]
+1 for getting it working with nonpdrm. With pkgi it's pretty much the de facto way of using taihen.

With no PlayStation account I'm just looking for a nice way to backup the save data. Really boggles how Sony could think it's a good idea
