### ISSUE TITLE
Make it compatible with NoNpDrm

### ISSUE THREAD

**Issue by masoudr** [d3m3vilurr/vita-savemgr#49]
Hi,
I'm using this tool with my vitamin games. Now I want to migrate my games to NoNpDrm version. How can I use my old save games with new dumps?
Thanks.

**Comment by wizardt** [comment]
Try use it as you did. And if games can't run，try delete GAME CODE folder in folder“patch” like “PCSB000891” created by savemgr.

**Comment by masoudr** [comment]
@wizardt Thanks, yes you are right I tried that and it worked like before. I forgot to write here.
