### ISSUE TITLE
Failure to recognize the games

### ISSUE THREAD

**Issue by joljolmax** [d3m3vilurr/vita-savemgr#5]
![2016-09-16-234337](https://cloud.githubusercontent.com/assets/22250351/18605567/832d24ec-7c6b-11e6-9c92-dcd50c3bf127.jpg)
![2016-09-16-233851](https://cloud.githubusercontent.com/assets/22250351/18605569/87a20fb0-7c6b-11e6-81c8-70832d5c967a.jpg)

After open the program does not recognize the games and pressing some d-pad button ends in error

**Comment by d3m3vilurr** [comment]
This bug fixed #2. ASAP I will release new version.
