### ISSUE TITLE
one piece pirate warrior 3 savagame

### ISSUE THREAD

**Issue by kanogunz0789** [d3m3vilurr/vita-savemgr#51]
help i have one piece pirate warrior with save game 70% dumped with vitamine now i move my save game in my computer and i download one piece pirate warrior of nonpdrm torrent instaled correctly and it work fine after i move my old save game with 70% the file is corrupted 'c0-11138-4' plz how i solve this problem I don't want to start all over again of 00

**Comment by f4f4f4f4** [comment]
Vitamin/Mai is decrypted, and the save file is decrypted. NoNPDRM is still encrypted and the save file is encrypted. That's why it's not compatible. Put your Vitamin version of the game back on and your save will work.
