### ISSUE TITLE
Software will not work on 3.65/3.67

### ISSUE THREAD

**Issue by TheOfficialFloW** [d3m3vilurr/vita-savemgr#53]
Because Sony fixed the ability to launch non-pfs from ux0:patch :P

**Comment by d3m3vilurr** [comment]
maybe  it's time to reimplement to kernel plugin.

**Comment by devingDev** [comment]
Can you somehow else get your saves back on 3.65 ?

**Comment by GabyPCgeeK** [comment]
Got vita-savemgr "working" using a modified rePatch(added patch for sceIoOpenForDriver to be able to redirect eboot.bin) and modified vita-savemgr(changed the copy to ux0:patch/ID to copy eboot.bin to ux0:rePatch/ID/eboot.bin). Haven't tested it on 3.65 only on 3.60 so don't know if the "non-pfs from ux0:patch" would affect it also.

Need people to test on 3.65.
[https://github.com/GabyPCgeeK/vita-savemgr/releases/latest](https://github.com/GabyPCgeeK/vita-savemgr/releases/latest)
[https://github.com/GabyPCgeeK/rePatch/releases/latest](https://github.com/GabyPCgeeK/rePatch/releases/latest)

**Comment by dots-tb** [comment]
@GabyPCgeeK hi, I'm the dev for rePatch. Do you think there is enough of a demand to merge this with main repo (or a do similar code)?

**Comment by GabyPCgeeK** [comment]
Don't know. The rePatch mod should also make game patches with patched eboot.bin work so maybe people are interested in that feature. Also I have only tested it with vita-savemgr in a few games so it needs more testing.

**Comment by xadox-1st** [comment]
@GabyPCgeeK Your solution is working for me on Enso 3.65. Thx for that.

**Comment by Leonyan938** [comment]
@GabyPCgeeK Works for me as well. So far haven't found any bugs yet. Tired on a few NONPDRM games. 

Also by using your method I no longer need to delete the game title folders in the patch folder like I used to do in 3.60 after backup NND games by using SAVEMRG.  

Until the new version of SAVEMRG release I believe your solution is the best.

Thanks a million for making this awesome software works in 3.65 again!!

**Comment by AlternativeZero** [comment]
@GabyPCgeeK Not sure if this is an issue of [savemgr](https://github.com/GabyPCgeeK/vita-savemgr) but when I tried to restore a savedata for Omega Labyrinth (PCSG00550) the eboot.bin wasn't returned to it's proper location instead I had to manually move it back to ux0:app.

I haven't encountered this issue when using savemgr on 3.60.

**Comment by remlei** [comment]
yeah it happens to me too, in my case, the eboot.bin on ux0:app is gone. I dont know why that happen.

**Comment by GabyPCgeeK** [comment]
Uploaded a new version that shouldn't delete existing files in rePatch.

**Comment by dots-tb** [comment]
@GabyPCgeeK did you restore the backup capability ?

**Comment by GabyPCgeeK** [comment]
@dots-tb it should backup existing eboot.bin in rePatch to eboot.bin.orig and then restore it.

**Comment by remlei** [comment]
ugh, tried the 2nd version, it still deletes eboot files on app folder (god why.... the app shouldnt be touching any files there).

**Comment by d3m3vilurr** [comment]
a new version will fix an issue.
