### ISSUE TITLE
can't backup,the game got a c2-14646-1 error

### ISSUE THREAD

**Issue by shirokuuhaku** [d3m3vilurr/vita-savemgr#55]
excuse me
I tried to backup my psvita"s savedata with the vita-savemgr
,but the game get a c2-14646-1 error
when I delete the sealedkey,there is no more c2-14646-1 error. but no savedata dected in the game also i can't backup
what can I do to save my savedata?

**Comment by d3m3vilurr** [comment]
probably fixed after 2.0.0 tree
