### ISSUE TITLE
Can you a a option to switch x and o

### ISSUE THREAD

**Issue by Conan179** [d3m3vilurr/vita-savemgr#59]
Hello@all.
Can you add a option to switch o an x?
 i use a EU vita and the X is axceppt and O exit.
greetz

**Comment by d3m3vilurr** [comment]
app used system default confirm button. and it can change henkaku setting in system setting app. not work??

**Comment by Conan179** [comment]
![2018-04-10-180128](https://user-images.githubusercontent.com/1906242/38568676-836bdec2-3ce9-11e8-9849-c9c00fb9f95c.jpg)
![2018-04-10-180146](https://user-images.githubusercontent.com/1906242/38568677-838a609a-3ce9-11e8-8cce-d77b5c08a3ce.jpg)
Nope

**Comment by d3m3vilurr** [comment]
i'll check that. thanks, report.
