### ISSUE TITLE
Error When Opening Game A Second Time

### ISSUE THREAD

**Issue by ItsDeidara** [d3m3vilurr/vita-savemgr#6]
I was able to dump the saves for The Binding Of Isaac once without issue. However upon reopening the app the app would not even try to initialize with the game. It would just state "error" without any other context. This did happen after I left vita shell(used FTP) could VitaShell maybe have caused a conflict? Rebooting the system did not help. Is there a log that I can provide that may give you more information?

**Comment by ItsDeidara** [comment]
The error occurs in the first step when it wants to rename eboot.bin => eboot.bin.orig. If there is already an eboot.bin.orig it will error out.

**Comment by d3m3vilurr** [comment]
hm.. i don't know why you cause that.

can you share did it?
1. force close app in save dumper
2. if answer is yes about first question, you try to remove game in home screen or to reinstall in vitashell?

i think, if you can get error like these step
1. force close in dumper
2. remove app
3. launch savemgr ; then got error
4. reinstall app
5. retry savemgr; but now you cannot launch dumper mode.

is this similar your actions?

**Comment by basso556** [comment]
what is the error code?
