### ISSUE TITLE
Add option to config file to use ur0 or ux0 as a backup folder.

### ISSUE THREAD

**Issue by alpakeno** [d3m3vilurr/vita-savemgr#60]

**Comment by Conan179** [comment]
i think, ur0 ist not a good idea for backups.

**Comment by alpakeno** [comment]
@Conan179 I'm curious why?

I think it's a good option. I'm using sd2vita, so sometime when i switch between it,
I cannot restore the savedata, but if it's in ur0 it will be able to restore\backup without issue.

**Comment by d3m3vilurr** [comment]
`ux0:data/savedatas` have the historical reason. and homebrew application should use `ux0:data` for the storing userland level data.
but really want to this?

**Comment by alpakeno** [comment]
@d3m3vilurr you're right, but as I said before I'm switching between sd2vita miscrosd and vita card
so I will be benefit by using the ur0, however by making ux0 is the default primary one,
and ur0 is a secondary, which can be changed from the save manager file will be a good option at least for me and anyone using it... it's up to you.

**Comment by d3m3vilurr** [comment]
okay, added enhancement tag, but it's low priority than the bugs ;-)

**Comment by alpakeno** [comment]
@d3m3vilurr sure, take your time :)

**Comment by alpakeno** [comment]
@d3m3vilurr I made a pull request for this one ( this is the first time for me ) but i have an idea for the choice in config menu.
can you make it also change the path instead of changing it from the config file using vita input message?

**Comment by alpakeno** [comment]
@d3m3vilurr It seems that i cannot make pull request in your repo.
here is the patchfrom my repo:
https://github.com/alpakeno/vita-savemgr/pull/1

**Comment by d3m3vilurr** [comment]
@alpakeno update last nightly then just change base path in your config.ini like `base=ur0:/data/savegames`
