### ISSUE TITLE
there is a problem with vita-savemanger2.0

### ISSUE THREAD

**Issue by bingzhihuxi** [d3m3vilurr/vita-savemgr#65]
eroor c2-12828-1
uxo:data/psp2core-1523436445-0x00001827e9-eboot.bin.psp2dmp
 
error c2-12828-1
uxo:data/psp2core-1523429619-0x000048223f-eboot.bin.psp2dmp

**Comment by d3m3vilurr** [comment]
please upload files...

**Comment by bingzhihuxi** [comment]
I am bingzhihuxi
Savemanger1.0 can use,but savemanger2.0 can not use. 
I like savemanger2.0 and hope to fix it as soon as possible. 
Thanks!

**Comment by bingzhihuxi** [comment]
old E-mail can only receive and can not send.

At 2018-04-12 14:45:49, "bingzhihuxi" <18289533807@163.com> wrote:

I am bingzhihuxi
Savemanger1.0 can use,but savemanger2.0 can not use. 
I like savemanger2.0 and hope to fix it as soon as possible. 
Thanks!
