### ISSUE TITLE
Can't do anything on Release 2.0.0

### ISSUE THREAD

**Issue by retosik** [d3m3vilurr/vita-savemgr#73]
Backing up gives an error, restoring gives an error. Earlier release (cui) worked fine.

https://i.imgur.com/dcGCAUJ.png

https://drive.google.com/open?id=1oHDiIaiV388x10oIcGHfNOhHh79BxDRi

**Comment by retosik** [comment]
Now I reverted to 1.0.0 and it corrupts every game i launch (gives an error 'this game is corrupt') and the game stays like that even after restart. Wth. It wasn't like this before.

**Comment by alpakeno** [comment]
After installing v2.0 reboot your vita and try again.

**Comment by retosik** [comment]
@alpakeno 
Thank you very much, succesfully restored save now. I thought I rebooted then... well, whatever.

**Comment by HWNJ** [comment]
Still the same, even restarting.....
