### ISSUE TITLE
Import save from different PSN account (enhancement?)

### ISSUE THREAD

**Issue by retosik** [d3m3vilurr/vita-savemgr#75]
I tried importing save made with savemgr made on different PSN account, but it results in a "You can't earn trophies in this application" warning. Is it technically possible to implement a method that converts the save to one compatible the current account so trophies work or not?

**Comment by d3m3vilurr** [comment]
hm.... maybe current logic occur the problem...

**Comment by SilicaAndPina** [comment]
try changing the ACCOUNT_ID feild in the param.sfo. . .

**Comment by retosik** [comment]
Thank you @SilicaAndPina, just did it and it works. Cheers!

**Comment by d3m3vilurr** [comment]
@SilicaAndPina @retosik is only needs change `ACCOUNT_ID`, or need other works?

**Comment by SilicaAndPina** [comment]
pretty sure its just ACCOUNT_ID feild.. why would it be stored anywhere else?

**Comment by d3m3vilurr** [comment]
i was test on non-decrypt mode, in that case something broken. only can edit on decrypt mode. i just made a question before test on the decrypt mode.

**Comment by abdulmuhaimin-work** [comment]
I tried using 2 different vita with 2 different PSN account. I just copied from the ux0:data/savegames right?But still got the save data corrupt problem. I used the latest nightly on both vita.
The host vita was on 3.68
the receiving vita was on 3.60. 
Im not too sure what I should do. 
btw, what did @SilicaAndPina suggest as solution? I cant see

**Comment by d3m3vilurr** [comment]
@abdulmuhaimin-work 
I don't know why she remove the comments,
she said `try changing the ACCOUNT_ID feild in the param.sfo. . .`
in my test it needs to jump into decrypted mode like vita shell.

`copy_slot_to_savedata` of the `main.c` will do 1) check the directory 2) decrypt the data storage(via `pfs_mount`) 3) copy real data 4) overwrite `ACCOUNT_ID` if it didn't same before

i didn't test to copy from upper version to lower. did you break every game savedata?
and can you give the game name and save data through the email?
d3m3vilurr at gmail.com
