### ISSUE TITLE
Still not decrypting Gundam Breaker 3 Asia Version

### ISSUE THREAD

**Issue by ness151** [d3m3vilurr/vita-savemgr#8]
It now successfully dumps the save, but the save is still encrypted.

**Comment by d3m3vilurr** [comment]
I was tested, can decrypt.
please check `ux0:data/rinCheat/PCSH00208_SAVEDATA/sce_sys/sdslot.dat`.
you can show `GUNDAM BREAKER3` string.

**Comment by ness151** [comment]
It's not decrypted on mine.

**Comment by ness151** [comment]
unless you're testing it with a physical cartridge, then your sdslot.dat and savedata are always going to be decrypted.

Is this tool only for digital versions?

**Comment by d3m3vilurr** [comment]
hm.. actually this tool support both types cart and digital, but i'm not have cart, so only test digital version.
please share your ux0:user/00 directory information

**Comment by d3m3vilurr** [comment]
can you share your add.db to my email. d3m3vilurr at gmail.com. i will check another exception case.

but, maybe i cannot handle this case before someone donate physical copy or find another case.

**Comment by ness151** [comment]
Here are my app.db and my entire ux0:/user/ folder https://mega.nz/#!PBsBBaZT!FAGi28cozk3cbRq3rb6uWvp1W1DzIM9Wz8lpYy-lq1k

**Comment by d3m3vilurr** [comment]
can you retest remove(or move) ux0:user/00/savedata/PCSH00208 directory?
i don't know why you have both directories..

**Comment by ness151** [comment]
The game creates that directory every time.

**Comment by ness151** [comment]
I deleted that directory, I dumped the save again, and it still is encrypted.

**Comment by d3m3vilurr** [comment]
i mark this issue to `pending`. i cannot handle now, it need retail cartridge for fix.

**Comment by ness151** [comment]
Damn, I guess I'm outta luck.  It seems like I was the only person who bought the physical version.

**Comment by d3m3vilurr** [comment]
@ness151 nope. you are totally right. people must buy retail copy for play game.
but i don't like gundam contents, it's my reason why i haven't retail cart.
in this case, actually need asia version, but i think, my friends also not have this version's copy.
