### ISSUE TITLE
VERY OLD version shown as latest on github!

### ISSUE THREAD

**Issue by devingDev** [d3m3vilurr/vita-savemgr#82]
https://github.com/d3m3vilurr/vita-savemgr/releases/latest

if you go here it shows a version from 2016...

also if you to https://github.com/d3m3vilurr/vita-savemgr/releases

the first version on top is that one as well.

fixpls # # @

**Comment by d3m3vilurr** [comment]
not old version. nightly means `daily build of dev line`. it's a future release version. :)

**Comment by devingDev** [comment]
why dont u just make a new release for each one 🤦‍♂️

**Comment by d3m3vilurr** [comment]
I want to built and release at every push. but also want to avoid tagging every commits. so I decide reusing the tag.
