### ISSUE TITLE
Add more view modes 

### ISSUE THREAD

**Issue by Monumilnides** [d3m3vilurr/vita-savemgr#89]
The interfaz with the icons it's beautiful but I think that would be great if you could add more view modes like, list, details, etc. Sorry for my English. Thanks for your time.

**Comment by d3m3vilurr** [comment]
current nightly already have list mode (maybe can change option button in the future)
`press select->move view mode->press confirm(o or x)->then press exit(x or o)`

**Comment by Monumilnides** [comment]
Thank you very much d3m3vilurr!

**Comment by Monumilnides** [comment]
I found a bug in the current nightly, may I open a new issue?
When the only button option is active (in this case list view active too) the slots in backup mode go crazy with the time an date numbers.
