### ISSUE TITLE
encryption problem if title id not match real game id

### ISSUE THREAD

**Issue by d3m3vilurr** [d3m3vilurr/vita-savemgr#9]
- Gundam Breaker3 AS
- YS8

**Comment by llakssz** [comment]
Good luck!
I'm not sure how to ask you, I don't have twitter!
Why do you have to do this 3 times?
https://github.com/d3m3vilurr/vita-savemgr/blob/master/main.c#L43

Thanks!

**Comment by d3m3vilurr** [comment]
screen cleaning need 3 times frame buffer switching. cuz vita use triple framebuffer.

**Comment by llakssz** [comment]
Thanks, very helpful!

**Comment by d3m3vilurr** [comment]
Related #13
