### ISSUE TITLE
Feature request: Transfer saves between PSVita and PSTV

### ISSUE THREAD

**Issue by IngwiePhoenix** [d3m3vilurr/vita-savemgr#96]
Hello!

When I bought my PSTV, I had fallen for the illusion of it being a system that interacts with the Vita and would allow me to play _all_ games on the TV... but, as mentioned, that was one big illusion. Instead, I had to learn that games were whitelisted (fixed, thanks to homebrew) and transfering saves between the two systems was a nightmare and a half (Persona 4 Golden is round-about a gigabyte and some - and takes forever to transfer...).

Now, currently the best way to go is to export the savegame using this tool and re-install it on the other system. But seeing as VitaShell has the ability to transfer directly between systems, I wonder if it would be possible to:

- either transfer saves directly between systems (via WiFi or Bluetooth)
- or to allow one to specify an external server (like a WebDAV server) to upload saves to and download them on the other system.

I am not an expert in the Vita's C API myself (let alone there possibly being some C++ too...), but from what I gather, it might just be easier to utilize WebDAV as hardware access - to transfer via WiFi or Bluetooth - might be harder to realize than a simple subset of HTTP(S).

As far as I am aware, WebDAV is basically HTTP, but with some commands added to mimic a filesystem - and to run it via HTTPS, a SSL/TLS socket is simply being used to negotiate the secure connection, and then send regular HTTP commands through. Which, I guess, also works for WebDAV.

Do you think you will implement such a feature? I'd happily help out with local building and testing! I do have a running Vita SDK:

```
$ /usr/local/vitasdk/bin/arm-vita-eabi-gcc --version
arm-vita-eabi-gcc (GNU Tools for ARM Embedded Processors) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
(Host platform is macOS 10.14.5, x86_64)

And a PSVita and PSTV both running 3.60 with h-encore/Ensō.

Kind regards, Ingwie.

**Comment by d-rez** [comment]
I believe #71 would work for you if it's ever implemented and would cover a much bigger userbase than people having 2 different systems and servers to upload files to

**Comment by IngwiePhoenix** [comment]
This is kind of what I meant - some cloud storages can be accessed via WebDAV, while some require a specific API. Since transfering between two devices directly might be harder to do, taking the route via cloud storage - or WebDAV - might be easier to implement.

**Comment by d3m3vilurr** [comment]
I don't like plain webdav, but I agree that is easier way and it might needs only curl.
another cloud system requires to implement oauth and api actions.

anyway it was duplicated #71 :)
