### ISSUE TITLE
Request: option to name each slot and backup all saves on system

### ISSUE THREAD

**Issue by Redpad** [d3m3vilurr/vita-savemgr#97]
Would be nice if there was an option name each slot, so its easier to know at what point it was made in the game, for people that use multiple save slots.

Also an option to just backup all games saves to a single folder or zip file. So people can periodicaly backup everything in case their system dies

Something that we could easily transfer saves directly to pc, or cloud system would be nice too

**Comment by d-rez** [comment]
I think all your ideas are already covered by the following existing issues:

#84 - export all
#71 - cloud storage
#61 - zip
#76 and #77 - slot names and more slots

**Comment by d3m3vilurr** [comment]
thanks @d-rez to restore my old memory :)
it duplicated #77 & #84
